#!/bin/bash
LOCAL_PATH=$(dirname ${BASH_SOURCE[0]})

# set path
if [ -f $LOCAL_PATH/get_pipenv_path ]
then
    SRC_HOME=$LOCAL_PATH/src
    WORKON_HOME=`$LOCAL_PATH/get_pipenv_path`
else
    SRC_HOME="$KALRAY_TOOLCHAIN_DIR/share/oran_ccl_tools/src"
    WORKON_HOME=`$SRC_HOME/../get_pipenv_path`
fi


# basic checker
if (($# < 1))
then
    echo
    echo "Usage $0 <inputfile>"
    echo
elif [ -f "$1" ]
then
    # translate relative path of arg 1 to absolute path
    # (okay, realpath do the same, but that's so funny)
    inputfile=$(cd "$(dirname "$1")"; pwd)/$(basename "$1")

    # run
    cd $SRC_HOME && pipenv sync && pipenv run python ccl_parser_main.py $inputfile && cd -
else
    echo "File '$1' not found"
fi
