#!/bin/bash

if [ -d "/work1/" ]; then
    BASEDIR="/work1/$USER"
elif [ -d "${HOME}" ]; then
    BASEDIR="${HOME}"
else
    BASEDIR="/tmp"
fi

PIPENV_PATH="$BASEDIR/.local/share/virtualenvs/ccl_tools"

echo $PIPENV_PATH
